# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3QqAuwVny878R7IzrDV83J33P007CY2
"""

import os
import time
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import schedule

# Set the exact path to your dataset
DATA_PATH = "/content/retail_sales_dataset.csv"

def run_pipeline():
    print("🚀 Starting automated pipeline execution...")

    # 1. Verify File Existence
    if not os.path.exists(DATA_PATH):
        print(f"❌ Error: File not found at {DATA_PATH}. Please check the path or upload the file.")
        return

    # 2. Extract Data
    df = pd.read_csv(DATA_PATH)

    # 3. Transform & Aggregate Metrics
    category_summary = (
        df.groupby("Product Category")[["Quantity", "Total Amount"]]
        .sum()
        .sort_values(by="Total Amount", ascending=False)
    )

    # 4. Save CSV Report
    report_csv_path = "/content/sales_summary_report.csv"
    category_summary.to_csv(report_csv_path)

    # 5. Generate & Save Visualization
    plt.figure(figsize=(8, 5))
    sns.set_theme(style="whitegrid")
    sns.barplot(
        x=category_summary.index,
        y=category_summary["Total Amount"],
        palette="viridis"
    )
    plt.title("Total Revenue by Product Category", fontsize=14)
    plt.xlabel("Product Category")
    plt.ylabel("Total Revenue ($)")
    plt.tight_layout()

    chart_path = "/content/category_revenue_chart.png"
    plt.savefig(chart_path)
    plt.close()

    print(" ✅ Pipeline completed successfully!")
    print(f"   - Report saved: {report_csv_path}")
    print(f"   - Chart saved: {chart_path}\n")

# Clear any previous schedule jobs
schedule.clear()

# Schedule the task to run every 10 seconds for quick testing
schedule.every(10).seconds.do(run_pipeline)

print("⏳ Scheduler active. Running 3 test iterations...\n")

# Run loop 3 times for demonstration so Colab doesn't hang indefinitely
for _ in range(3):
    schedule.run_pending()
    time.sleep(10)

print("🎉 Test completed! Check the left file panel in Colab to see your generated files.")